movies/urls.py
from django.urls import path
from . import views

app_name = 'movie'

urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('<int:movie_number>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_number>/update/', views.movie_update, name='movie_update'),
    path('<int:movie_number>/delete/', views.movie_delete, name='movie_delete'),
    path('<int:movie_number>/scores/new/', views.score_create, name='score_create'),
    path('<int:movie_number>/scores/<int:score_number>/delete/', views.score_delete, name='score_delete'),
]

project_07_db/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls'))
]

movies/models.py
from django.db import models


# Create your models here.
class Genre(models.Model):
    name = models.TextField(default='')


class Movie(models.Model):
    title = models.TextField(default='')
    audience = models.IntegerField(default='')
    poster_url = models.TextField(default='')
    description = models.TextField(default='')
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)


class Score(models.Model):
    content = models.TextField(default='')
    score = models.IntegerField(default='')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Genre, Score


# Create your views here.
def movie_list(request):
    movies = Movie.objects.all()
    context = {}
    context['movies'] = movies

    return render(request, 'movies/list.html', context=context)


def movie_detail(request, movie_number):
    movie_data = get_object_or_404(Movie, id=movie_number)
    score_data = movie_data.score_set.all()
    context = {}
    context['movie'] = movie_data
    context['scores'] = score_data

    return render(request, 'movies/detail.html', context=context)


def movie_update(request, movie_number):
    movie_data = get_object_or_404(Movie, id=movie_number)

    if request.method == 'GET':
        context = {}
        context['movie'] = movie_data
        return render(request, 'movies/update.html', context=context)
    else:
        # TODO: make update code
        return redirect('movie:movie_detail', )


def movie_delete(request, movie_number):
    movie_data = get_object_or_404(Movie, id=movie_number)
    if request.method == 'POST':
        movie_data.delete()

        return redirect('movie:movie_list')


def score_create(request, movie_number):
    movie_data = get_object_or_404(Movie, id=movie_number)

    if request.method == 'POST':
        score_data = Score()
        score = request.POST.get('score')
        content = request.POST.get('content')
        score_data.content = content
        score_data.score = score
        score_data.movie = movie_data

        score_data.save()

        return redirect('movie:movie_detail', movie_number)


def score_delete(request, movie_number, score_number):
    movie_data = get_object_or_404(Movie, id=movie_number)
    score_data = get_object_or_404(Score, id=score_number)

    if request.method == 'POST':
        score_data.delete()

        return redirect('movie:movie_detail', movie_number)

movies/templates/movies/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link h5 mb-0 {% block home_active %}{% endblock %}" href="{% url 'movie:movie_list' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link h5 mb-0 {% block detail_active %}{% endblock %}" href="">Movie Info.</a>
            </li>
        </ul>

        <form action="{% url 'movie:movie_list' %}" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
<div class="container">
    {% block body %}
    {% endblock %}
</div>


<!-- JS CDN -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

movies/templates/movies/detail.html
{% extends 'movies/base.html' %}

{% block title %}
    Movie Detail
{% endblock %}

{% block detail_active %}
    active
{% endblock %}

{% block body %}

    <!-- Movie Information -->
    <h1 class="display-4 mt-5">영화 정보</h1>
    <hr style="border-color: black">

    <section class="row mt-5">
        <div class="col-4">
            <img src="{{ movie.poster_url }}" class="card-img-top d-flex justify-content-center"
                 alt="{{ movie.title }}">
        </div>
        <div class="col-6 offset-1">
            <h1 class="mt-2 mb-4">{{ movie.title }}</h1>
            <h2 class="mt-2 mb-4">장르: {{ movie.genre.name }}</h2>
            <h4 class="mt-3 mb-4">관객수: {{ movie.audience }}명</h4>
            <hr style="border-color: black">
            <h5 class="mt-5">{{ movie.description }}</h5>

            <div class="d-flex flex-row align-items-end mt-5">
                <form action="{% url 'movie:movie_list' %}" class="mr-3">
                    <button type="submit" class="btn btn-outline-success">Movie List</button>
                </form>
                <form action="{% url 'movie:movie_update' movie.id %}" class="mr-3">
                    <button type="submit" class="btn btn-outline-warning">Edit</button>
                </form>
                <form action="{% url 'movie:movie_delete' movie.id %}" class="mr-3" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                </form>
            </div>

        </div>
    </section>


    <h1 class="display-5 mt-5">영화 한줄평</h1>
    <hr class=" mb-3" style="border-color: black">

    <!-- Score Creation -->
    <div class="row">
        <div class="col-6">
            <form action="{% url 'movie:score_create' movie.id %}" method="POST" class="form-inline form-row mt-3">
                {% csrf_token %}
                <label for="score"></label>
                <input type="number" name="score" id="score" class="form-control" placeholder="평점">

                <label for="content"></label>
                <input type="text" name="content" id="content" class="form-control ml-3" placeholder="한 줄 남기기">

                <button type="submit" class="btn btn-outline-dark ml-3">Submit</button>
            </form>
        </div>

        <!-- Score List -->
        <div class="col-6 mt-3">
            {% if scores %}
                <table class="table">
                    <tbody>
                    {% for score in scores %}
                        <tr>
                            <td>{{ score.score }}</td>
                            <td>{{ score.content }}</td>
                            <td>
                                <form action="{% url 'movie:score_delete' movie.id score.id %}" class="col-3"
                                      method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-outline-danger btn-sm">delete</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>

            {% else %}
                <li class="list-group-item">No scores yet...</li>
            {% endif %}
        </div>
    </div>

{% endblock %}

movies/templates/movies/list.html
{% extends 'movies/base.html' %}

{% block title %}
    Movie List
{% endblock %}

{% block home_active %}
    active
{% endblock %}

{% block body %}

    <h1 class="display-3 mt-5 text-center">Movie List</h1>
    <hr style="border-color: black">

    <div class="row mt-5">
        {% for movie in movies %}
            <div class="card border-dark col-4 col-md-2 offset-1 mt-5 mb-3 px-1">
                <img src="{{ movie.poster_url }}" class="card-img-top" alt="{{ movie.title }}">
                <hr>
                <div class="card-body pt-1 pb-3">
                    <a href="{% url 'movie:movie_detail' movie.id %}" class="card-text">{{ movie.title }}</a>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

movies/templates/movies/update.html
{% extends 'movies/base.html' %}

{% block title %}
    Movie Update
{% endblock %}

{% block body %}
{#    TODO: make update html#}
{% endblock %}